### ISSUE TITLE
I am trying to solve my captcha, but got a error.

### ISSUE THREAD

**Issue by liaocjzz** [kavishdahekar/IITG-Captcha-Solver-OpenCV-TensorFlow#4]
>>python solveCaptcha.py captcha.jpg
>>
Model restored from file : training/trainedModels/softmaxNNModel.model40 x 100
Traceback (most recent call last):
  File "solveCaptcha.py", line 131, in <module>
    temp_image = np.reshape(tempthresh, (1, 2925))
  File "E:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "E:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1800 into shape (1,2925)

I guess that's because my captcha is not the same size of yours.
So how can I achieve crack my own cpatcha?

**Comment by kavishdahekar** [comment]
Ah right!
I shouldn't have hard-coded those values, apologies for that.

So the number 2925 is simply the product of the width and height (64*45) of the individual alphabets extracted from the captcha. In my case the individual alphabets were 64x45 pixels which I then flattened into a 1x2925 matrix.

If you check segregate.py line 113, I am setting the character Height to the same height as that of the captcha image(which was 64 pixels) and character width to explicitly 45 pixels. Try to play around with these and find what suits your captchas the best. Once you have these values, their product would be the value you need to replace 2925 with. That should hopefully solve your problem.

Let me know if you need any more help.

**P.S You can remove all the hard-coded values and create a globally available config structure where all these values can be set and retrieved. Please create a PR if you would like to contribute.**
